# 输入：s = "aababbab"
# 输出：2
# 解释：你可以选择以下任意一种方案：
# 下标从 0 开始，删除第 2 和第 6 个字符（"aababbab" -> "aaabbb"），
# 下标从 0 开始，删除第 3 和第 6 个字符（"aababbab" -> "aabbbb"）。
#
# 链接：https://leetcode.cn/problems/minimum-deletions-to-make-string-balanced
import collections
import sys


class Solution:
    def minimumDeletions(self, s: str) -> int:
        # 思路不对
        # i = 0
        # j = len(s) - 1
        # while i <= j and s[i] == "a":
        #     i += 1  # i的位置是b
        # print(i)
        # while j >= 0 and s[j] == "b":
        #     j -= 1  # j的位置是a
        # print(j)
        # if i == len(s) or j == -1:
        #     return 0
        # count_a = collections.Counter(s[i:])
        # count_b = collections.Counter(s[:j + 1])
        # return min(count_a["a"], count_b["b"])
        i = 0
        min_ = sys.maxsize
        a_, b_ = 0, 0
        sum_a = collections.Counter(s)["a"]
        sum_b = collections.Counter(s)["b"]
        while i < len(s) - 1:
            if s[i] == "a" and s[i + 1] == "b":
                c_b = b_
                c_a = sum_a - a_ -1
                min_ = min(min_, c_a + c_b)
            if s[i] == "a":
                a_ += 1
            else:
                b_ += 1
            i += 1
        return min(min_, sum_a, sum_b)


if __name__ == '__main__':
    res = Solution()
    print(res.minimumDeletions("bbaa"))  # 2
    print(res.minimumDeletions("a"))  # 0
    print(res.minimumDeletions("b"))  # 0
    print(res.minimumDeletions("aba"))  # 1
    print(res.minimumDeletions("bab"))  # 1
    print(res.minimumDeletions("bbbb"))  # 0
    print(res.minimumDeletions("aabb"))  # 0
    print(res.minimumDeletions("ababaaaabbbbbaaababbbbbbaaabbaababbabbbbaabbbbaabbabbabaabbbababaa"))  # 25
    print(res.minimumDeletions("baba"))#2
    print(res.minimumDeletions("bbbaa"))#2
    print(res.minimumDeletions("baaa"))#1
    print(res.minimumDeletions("bbaaa"))#2
    print(res.minimumDeletions("abababa"))#3
    print(res.minimumDeletions("babaab"))#2
    print(res.minimumDeletions(
        "abbbaaaabaabbaaabbabaaabaaaaaaaabbaababbabbaabbbaaabbbabaabbbaabbbabbaababbaaabaabaaabaaaaaabbabbbabaaaaaaaaababaabbabbbabaaabbbababaaabaababaaababbaabaaaabaaaaabbabbaabbbaabbbbaaabaaabbbaaaaabbaabaabbaaabaabbabbabaaabaaaaabbbaababbaabaaabbabbaabbabbbbabbbbbbbabbbaaaabbaababbaaaabbbbbbaabbbbbbaaabbabababbabbabaaaaabbaaaabbbaababababababbbaaabaaababbbabbaabaabbbbabbbababaabaabaabbabbaabbaaabaaaaaaabbbbababbabbabababbbaababbbababbabaabbbbbabbbbaababbbbbabaaaabbbbbbabaaabaaabbbabbbaabaabbbabaaaaaabababbabbbababbbaaabaabaaabaababbaaaabbbbbbabbbbabaabaabbabbbaaaabaabbbababbabaabababbbbaababbbabbbbbababaaaabbbababbaabaaaababbaaaabbbabbbaaababbbbabbbbabababaabbaaababbaabbbaaabbabaababbabbbbbaabababbababbbbbbaaabbbbbbababaaabbaabbbbbabbbaabbbaabaabbbaabbabbbabbaaaabbbbabbbbaabbbaaabbbaaaabaaaaaabbbbaaababbbaaaabbbbabaabaabbaababbbbbbaaaaaabbaababbabbaababaababbbaabababbabbbbbababbbabbabbaaaabbbbabbbbabaaabbbabbababbbaabaaababaaaabbabbbbbbabaabababaaaaabbbbbbbabbbbaaaaabaaaaaaaaaababaaabaabbabaaabbaaaaabbabbaaaababbbaabaaaabaabaabbaaabbabbbabbbaabbbabaabbbababaabbaabaabbaabbbabbbabbbbbbabbbabbbbbbaaababbbbaabaabbaabbbbbaaaabaababbaabaaabbababbaabaabbaabbaaababbaaabbabbbaabaababbbaaaaabaaabababaabbbbbbaababbbaabbabbabababbbbabbaabaaaaaabbbbbbbaabbbaabbabababaabaaaababbabaaaabaabaabbbaabbaabbbbaaabaabbbbbbbaabaaaaabbaaabbaabaaaabaaababaaaababbbbbaabbabbaabbaaaababbbabbaabbaabbbbbaabaaabbaabbabaaaabbbbbaaabbabaaaabbbabbaaabaabaaaabaaaaaaabbaaaaaaaaabababbbbbaabaabbababaaabaaabaaaabbabaabbbababbbabbbabbbabaaabbabbbbaaabbabbbbababbaaabbababbbaababbaaaaaabbbaabaababaabaabbbbbabbbababaabbbbaabaabaabbaaababbabbaaabbaabbabbbabaababbbabaaababbaaababbbabbaabbbbbbbaaaaabababbbbabbaabbabbbbbbbaaabbaaaaaabababbbabbabbabbbababbbaaaababaaabbabaabbbbaaabaabaabababaaabbaaaabbbbbababaabbbabababbaabababbaaaaaababbaabaaaababaababbaababababbbbbbbbbbbabbbabaabbaaaaaababaaaabaaabbababbaabaaabaaababababbbaabaaabbaaaaabaabaabaabaaabbbabbbabababbbabaabaaabbaaabbababaaababaababbbaaababaaaababaaabbaabbaabaabbabaabbaababababbaaabbabbbbbbaaabbbaaabbbbabbababbbbbabaaabaabbbaaabaabbbaaababaaabbababbbbaaaababbbaaabbaabaaabbaabbbabbbabbabaabbababbabbbbbaaaaaabbabababbbabbababbbabbbabaaabbbbbababaaabaaabbbbabbaaaababbaababaabababbbbbaababababbbabbbabbaabbabaaabaababaaaabaabbbaaababaaaaaabaaaabababbaaabaabaabbabbbbbbbababaabbbabbbabaaabbabbbabbaaaabbbbababbbaaababbaababbabbabbbbaababbbababbababbbaaaabbaabbabbaabbbbbbbbbababaabbaaabbbbaaaabbabbababbabaabbabaaabbbbababbbaabaabbabaabaabaaabaabaaaababbbbbaabaaabbbaabbbbbaaaabaaaaaabbbbbaabbaabbaabababbaabaaaaaabbaaabbabbbbbbbbaaaaabbabababbbaaabbbbaaaababaabbbbaabbbabaabbbaabbbbbbbabbbababbbaabaababaabbabbbbaaaaaababbaabaabaabbaabaabbaaaaaaabbbbbbbaabaabaaaabaababaaababababbabbabbbbbaaaaaabbbbabbbbaaababaaaaababaabaaaabababbbbbbaabbabbbbaaaaaaaaaaabbaabbbabbaabaaabbbbaabbbaabbaababbbbbbaaaaabbbbababbbbbbaabbabbaabbbaababbbabbaaaabbbbbbabaabaabaaaabaabaaaabaaabbabaaabbababbaabaaabbababbbbaabbbbabbbababbabbabbbbaabbbabaaababaaaaaababbbaaabaabaaabbaaabbaabbababaaabbbaabbabaabbbbabbaaabbbabaabbbbabaabaaabbaababaaabbbbaaaaabbbabbabababbbbaabbbaaabbabbaaaaabbbaaabbbbaaaaaababbbbbaabaabbaababbbbabababaabbaababaaaaaaaabbbbbbbaaabbbaabbabaabbabbaabbbaaabbbabbbbabbaababaabbbabbaaaaabaaabaabbbabaaaaaabbbbbbaaabababaabaabbbbaabbbbabaabbaaaabaababbbbaaaabbbabbabbbaababbbbababbaaababbaaaaabbaaaabbbbbabaaabbabababbaaabbabaaababbabbabbaabababbabaaababababbaababbabbbabaaaaababaabbbaaaababbbbabbbaaaabbbbbbbbbaaaabbaaaaaabaabbabbbbaaababaaaaaaabbbbbbbaabbbbbbbabbababbabaaaabbaaabbababaaabbbbbabbbbbaaabbaabaababbaaaabbbbababbabbababbaaabbbbabaabababbabbbbaabbaaabbbaababaabbabbaaaabbbbbbbabbaaaaaabbbbbababbbbabbabbabbbaababaaabaababbaabbbabaabbbbbabbbbbbaabbabbaababbbabaaaaabbaaababbbbabbaaabbbbaabaaaabbabbbbaaababaaababababbbaaabaaabaabababbbbabbbbbbbabbbbabababaaaaaaaaababababbaabbbabbabbbabbbbbabbabaabbababbbbbbaaabaabababbaaabbabaaababbabababaabaabbbaaabbabbbabbabbbbabbbbbbbbabbbaababababbbbaabaaababbaaaaabaaabbabababbbababbbaaaaaabaaaaaabbabbaabaaaaaabbaaaaabbbbbaaabaabaaabaaaaaabbbbaabbbaaababaaaaaaabbaaabbabaaaaabbaabaaaaaabaabbaaaaabbbabbbbbaaabbbbbbaaabababbbabababbaababbaaabbabbaaaabbbbbaaaaaabbaaaaabaabaababaabbabaaaaabbbbbaababbbaaabbabbbababbaabbbaaababaaababbbabbabbababaaabbaaababbabaabbbbababaabbbbaaabbbaabaaaabbbaaabaaaabbbabbaaaaaaabaaaabbaabababaabbbbaaabbababbabaaabbbaaababbbbbbbaaababaabbbaabbbaababaabbaababbaabbbbaabbabaabbbbbbbbbbaababaaabbabbaabbbaabbabaababbbabababbbbabbbaabaabbaabbbaaaaaabaaabbabbbbaabaaabbbbbabbbaababbaabaabbabaaaaaaaabaaababaababbbaaaabaabbbbabbaaaabbbaabbababbbaababbababaababbabbbbababbbaaaaababaaababababbabbbabababbaabaaabbaaababbabbabbbaabaabbbbaababaabbbaabababbababbbaaabababaabbaabbabaaabbaaabbaaaaabbbaabbbbababbabbababaaaabbbbabaabbbabbbbabbbaabababbaaaaaabbabbbaaaaaabbbaabaabaaababaabaaaaabababbaaabbabbbabbbaabbababbbbabbaabbababaaabaabaabbbababbbaabbbabbbaaaaaabbbbaaababbaabbabaababaaaaaabbbbbababababaaabbaabbbaaabbaaaaabbabbbbaabaababaabaaabaaaabbbabbbaaaaaaabbbbaabbbabbababbbabaababbbabbbaaabbbababbaabbbbbaabbaababbbabaabbabababbaaababbaaabaaaabaaaababbabbbbababbaabababbbabaababbbababbbbababababaaaaaabaabaaabababaaaaaabbaababbaabbabaaaaaaabaaabbaaaababaabbabaabbabbbbababbababbabababaabbbabbbbbbaabaaabbbabababbababaaaabbababaaabaaaabaaabababaaababababaaaaaaababababbbaaaabbabbbbbabbaababbabbbbabbbaaaaaaabababbaaaababaaabbbabaabaababbbbabbabbaabbbbbabbabbabaaaaababbababbbbbaababbbaabbbbaabaabbbaaabbbababaababaabbababaaabbbaabbabaaabbaabaabbbbbabbbabaababbabaababbbababaaaaaabababaabaabbaabbabbaaabbababbababaabbbbbaabaabaabbababababbaabbbaabbabaabbbabbbabbaaaaabbbabbbabaaabaaabbbababbaaaaaabbbbaabbbbbabaaaaabaaaabbaabbbababaababbbababaaaabbbbabbaaabaaaababababaabbaabaaababbbbbbbbabaaabbbbbbbababaaaabbbbbbbaabababbaabbaabbaabaaaabbbbababbababbaabbbababbbaabaabaabaaaabbbaabbbbababaabaaabaababaabbbbbbbababbbbbabbbaababaabaabababababaaabbaaaabaaabbabbaaabaaabababaabbabaababbbaabaaabaaaabbbaabbaaaabaaabababababaaaaabaabaaabbababbabbaababbbaabaaaaaabbbbabbabbbbabaaababbbabaabaaaaaaaaabbaaaaabaaabbabbabaaaabaabaabbaabaabbaaaababaabbbbbbabbbbaaababbbbbaaaabbaaaaabbbaaabbbabbaaaaababbbbbbaabbaaaaabaabbbbbababaabaabaaaabbbaaaaabbbbababbbbbaaabbaabaaabbbbabaabbaaabbababbbabbbaabaaabaabbabbabaaabbaaaaababaabaaabbbabaabaaababaaabaaaabbaaababaabbabaababbbbaabbaaabbbbaaababbabaaaabbabbabbbbbbbbbbaaaaabbbbbbaaaabbbaababbbabbaaababababbabaababbbbbbbaabbaabaaaaabaaabbabbbaababbbbabbaabababbabbabbabbbababbaaaaaabbabaababbaaaabbaabaaabbbaaaababaabaaaaabaaabbabaabbabbabaaaaabaaabbaaabbbabaaaaaaaabbbaababbbabbabbbbabaabbaabaaaabbabaaaaabbabaabbabaaabbabaabbbbabbbbabbbabababbabaabbbbbaaabbabbabbabaabbbbbaababaabababbabaaabbabaaababbaaabbbbbabababbaabaabbaaaabbbaabbabbbbaaaaaababbbbabbabaaabbaabaabbabaaaabababbababbbbbbbbabaaaaaabbaaaaaabaabaaaaaaaaabbbbabaaabbaabaaaabababaaaaaaabbbababbbbbababaabbbaabbbbbabbbbbbabbbaaabbaabaaabaabaaabbbbaabaabbbaabbaaaabbbbbaaaabbaababbabbaababbbbabaaabbabbbaabaaaaaaabbababbbababbbaaaababbbbbbaababbbabbbbbabaabbbbaabaaabbbaabababbababaaabbbabbaaabaabbaaaaaaaabbbaabababbaabbbbaabaabbaaaaabaabbbbaababaaaaababababbabaaababbabbaaabaabbbbbaaaabaabaaaabaaaaabaababaabababbbaababbbaabbabbbaabbabababbbbbaaabaababbbabbbaabaaabbabbabbaaabbaaabaaaabbbbabbabbaababbabbbabbababbbabbbaabbbaabababbbaabaabbabaaabbbbabbaabababaabbbbbbbbaabbbbabaabbbbabbbaababaaabbbbaaaaaabbbbaaabaabaaabbaaabbaaaaaabababbaababbaabaababbbabbabbabbaabbaaabbbbabbbbbbbaaaaaaaaaabaaaabaaabaaaaaabbbabaaaabbaabbababbbabbbbbbabbabbbabbbabbaaabaabbbbaaabaaaababbbabbaaaabbaaaabaabbaaabbabaabababaaabababbbbbbaaaabababbabaabaabbbbbbabbbbbabbbaaabbaababbaabaaababbbabbbaabaabbabaaabbbaabbbaabbbabaababbbaabaabbaaababbabbaabbbabbbbabbabbbbaaaabbbaabbabbbababababbbbbbababaabbabbbaaaaaaaabaaaaabaaaaabbaababaabaabaaaaaababbabaaababaabbbabbbaaaaababaabaaaaaaabbbbbababbaabbabbbaabbbbbababbabbbbaabaaaabbbbbaabbaaaaaaaabbababbbbaababbbaabbaaababbbaaaababbaaaababaaabbaaaabaaaaaaaaaababbaababbaaabbbbabbabbaaabababbabbbbabababbbabaabaabbbbbabababbabbaaababababbabbaabbbbabbbbabbbbbbbaabbaabbbbbbabbbbababbaababaabbabababbbabbbbaaaaababbaabbaaababaabbbbbabbbbaaababbaabbaababbabbaaabaaabaabababbaabbaababbaaaabbbbbaabbabbbaabbabbabaaababbabababbabaabbbabbabaaabaaabaabbabaaabaabbaabaababaabaababbbabaaabaabbbbaababaaabbbaabababaababbbaaababbabaababaaaabbababbabbbbbbabbaabbbbbaabbbbabaabbbaaaaaabbaabbabbabbabbaabaaabbbaaabbbbbbbbbbaaabbbabbbabbbaaaabbbbbabaabbbaaabbbbbbbbbbaabbaaaabaaabaaabaaaaabbbbaaabbbbaabbabaabaabababaaababaaaabababbbbaaaaaabbaabaaaaabbaaabbbbbbaaabbababbabbbaabbbbabbbabaaaaabbaaaabaaabbbabbbaaabbbbaabbbaaabaaaabaabbabababbaabaaababaaaaaaaababbbbbbaabaabbaabaaabbaababbaabababbabaaabbabbbbabbabbaaababbbababbaabbbbbbbbbaaaaabbabaaaabaabbbbababbbbaabbaaabbbbaaabbaababaabbbababaaabbabbbaabaaabaabaaaabbabbbabaaaaaaabbbababbabbababbbbaabaaababbbabbbbababaabbaaaababaababaaaaabaaabaabbaaabbbaaaabaaabaabbbbbbabbaabbbabaaabbabaabaaabbbabaaababaabaabbbbbabbababaababaaba"))
